spring:
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888



server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

