spring:
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: optional:configserver:http://host.docker.internal:8888
  data:
    mongodb:
      host: host.docker.internal
      port: 27017

server:
  port: 8082
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh,health-readiness,health-liveness
