spring:
  application:
    name: cards
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888



server:
  port: 8082

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh,health-readiness,health-liveness
