spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://host.docker.internal:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/accounts/**

        - id: loans-service
          uri: lb://LOANS
          predicates:
            - Path=/loans/**

        - id: cards-service
          uri: lb://CARDS
          predicates:
            - Path=/cards/**

        - id: customers-service
          uri: lb://CUSTOMERS
          predicates:
            - Path=/customers/**

        - id: gateway-server-routes
          uri: lb://GATEWAY-SERVER
          predicates:
            - Path=/gateway/**
          filters:
            - RewritePath=/gateway(?<segment>/?.*), $\{segment}

# Structured Logging Configuration
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: ""  # Disable default pattern, use JSON from logback config
  level:
    com.example.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    root: INFO

server:
  port: 8072

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true
