spring:
  application:
    name: customer
  profiles:
    active: dev
  config:
    import: optional:configserver:http://host.docker.internal:8888
  data:
    mongodb:
      host: host.docker.internal
      port: 27017

server:
  port: 8084
  address: 0.0.0.0

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh,health-readiness,health-liveness

info:
  application:
    name: ${spring.application.name}
    description: Customer Microservice
    version: 1.0.0
