spring:
  application:
    name: customers
  profiles:
    active: dev
  config:
    import: optional:configserver:http://host.docker.internal:8888
  data:
    mongodb:
      host: host.docker.internal
      port: 27017

# Structured Logging Configuration
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: ""  # Disable default pattern, use JSON from logback config
  level:
    com.example.customers: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    root: INFO

server:
  port: 8084
  address: 0.0.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true
