# cAdvisor - Container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      # Minimal required mounts for macOS to prevent race conditions
      - /var/run:/var/run:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # Mount the container hints file to provide explicit configuration
      - ./cadvisor-container-hints.json:/etc/cadvisor/container_hints.json:ro
    environment:
      - CADVISOR_STORAGE_DRIVER=
      - CADVISOR_HOUSEKEEPING_INTERVAL=30s
    command:
      - --disable_metrics=disk,diskIO,network,tcp,udp
      - --docker_only=true
      - --store_container_labels=false
      - --allow_dynamic_housekeeping=false
      - --housekeeping_interval=30s
      - --disable_root_cgroup_stats=true
      - --docker_only=true
      - --max_housekeeping_interval=60s
      - --event_storage_event_limit=0
      - --event_storage_age_limit=0
      - --container_hints=/etc/cadvisor/container_hints.json
    networks:
      - msnet
    restart: always
    privileged: true
