services:
  # config-server:
  #   build:
  #     context: .
  #     dockerfile: config-server/Dockerfile
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dev
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - msnet

  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://host.docker.internal:8888
    # depends_on:
    #   - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msnet

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://host.docker.internal:8888
    # depends_on:
    #   - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msnet

  loans:
    build:
      context: ./loans
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://host.docker.internal:8888
    # depends_on:
    #   - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msnet

  customer:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CONFIG_IMPORT=optional:configserver:http://host.docker.internal:8888
    # depends_on:
    #   - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - msnet


networks:
  msnet:
    driver: bridge

volumes:

