spring:
  application:
    name: loans
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

profiles:
  active: dev

server:
  port: 8083

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,refresh,health-readiness,health-liveness
