apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: Prometheus
    url: http://prometheus-service:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      
  - name: Tempo
    type: tempo
    access: proxy
    uid: Tempo
    url: http://tempo-service:3200
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'Prometheus'
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'Prometheus'
      search:
        hide: false
      nodeGraph:
        enabled: true