spring:
  application:
    name: accounts
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

