{
 "title": "Simple Microservices Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=~\".+\"}"
    }
   ]
  },
  {
   "title": "Accounts Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/accounts.log\"}"
    }
   ]
  },
  {
   "title": "Cards Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/cards.log\"}"
    }
   ]
  },
  {
   "title": "Loans Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/loans.log\"}"
    }
   ]
  },
  {
   "title": "Customers Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/customers.log\"}"
    }
   ]
  }
 ]
}