server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sameepmondhe/microservices-with-java.git
          search-paths: configs
          default-label: main
    bus:
      enabled: false

# Structured Logging Configuration
logging:
  config: classpath:logback-spring.xml
  pattern:
    console: ""  # Disable default pattern, use JSON from logback config
  level:
    org.springframework.cloud.config: INFO
    org.springframework.web: INFO
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true

