server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/configs/*"
          #search-locations: "file://Users//Sameep.Mondhe//learning//ms//microservices-with-java//config-server//src//main//resources//configs/"
        git:
          uri: https://github.com/sameepmondhe/microservices-with-java.git
          search-paths: configs
          default-label: main