server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sameepmondhe/microservices-with-java.git
          search-paths: configs
          default-label: main
    bus:
      enabled: false

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: refresh,health,info,health-readiness,health-liveness
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true

